### ISSUE TITLE
Create slack channel

### ISSUE THREAD

**Issue by joejulian** [gluster/community#13]
It has been pointed out that the one thing slack has going for it that IRC does not is the ease-of-use as a mobile application. Sure, it _can_ be done with IRC but it requires configuring and hosting external services where slack does not have that requirement.

Currently a "gluster" slack exists. We do not know who registered it.

I propose we just create "gluster-community" slack and use [slackin](https://github.com/rauchg/slackin) to have a more friendly url at slack.gluster.org.

**Comment by nigelbabu** [comment]
Would using Gitter.im solve the same problems? Given we already have a channel and some of us occasionally check-in. Yes, it's an extra app if you already have slack on your phones.

**Comment by amye** [comment]
@joejulian, can we bring this up in the next community meeting? Use the gitter we already have, implement a slack channel, next steps?

**Comment by amye** [comment]
Bad news: Slack announced today that they're removing their IRC gateways as of May 15th. If we're going to go down this road, we're going to need another way to have it be accessible. 
https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP

**Comment by amye** [comment]
Dropping back with an update, the Gitter channel is getting some use as part of the docs hackathon: https://gitter.im/gluster/glusterfs
