### ISSUE TITLE
Meetup kits / swag availability for community meetups / talks etc...

### ISSUE THREAD

**Issue by sammcj** [gluster/community#14]
@amye suggested I post this here (good idea!).

For example, I'm giving a talk next week at Infracoders Melbourne called something like 'Clustered, Distributed File & Volume Storage' demonstrating how we're implementing Gluster for use with our Kubernetes volumes.

It would be nice to have some tshirts and stickers to give away to promote GlusterFS.

Another thing I thought of would be a small fridge magnet with a link / QR to the GlusterFS website.

**Comment by amye** [comment]
This is back in action! 
I'm working with our fulfillment group this week to figure out the process to ship out meetup kits to people hosting a meetup. Global availability is a requirement for this. 

I'm hoping to be able to get this publicly available by the end of next week, Jan 19th.

**Comment by sammcj** [comment]
Legend, thank you Amye!

Hope you had a great holiday season.

--
Sam McLeod
https://smcleod.net
https://twitter.com/s_mcleod

**Comment by amye** [comment]
We are live on this: 
http://www.gluster.org/events/ has the link to http://www.gluster.org/meetup-swag-requests/!

**Comment by amye** [comment]
Fixing gluster.org/events, bad things have happened to the website.
