### ISSUE TITLE
docs.gluster.com has invalid SSL cert

### ISSUE THREAD

**Issue by sammcj** [gluster/community#15]
https://docs.gluster.org/en/latest/ needs a correct certificate installed for the domain, it's currently using the readthedocs wildcard cert.

![screen shot 2017-11-08 at 1 26 36 pm](https://user-images.githubusercontent.com/862951/32528770-f70ee218-c488-11e7-8572-a4733577aa69.jpg)

**Comment by sammcj** [comment]
Looks like a bug in readthedocs.io if you aren't self hosting :( - https://github.com/rtfd/readthedocs.org/issues/2652

**Comment by nigelbabu** [comment]
Already on our list of things to fix. We're going to point the DNS to a web server we own and proxy it back to RTD.

**Comment by nigelbabu** [comment]
Closing this in favor of an infra bug: https://bugzilla.redhat.com/show_bug.cgi?id=1511263
