### ISSUE TITLE
Gluster docs have poor search result quality

### ISSUE THREAD

**Issue by sammcj** [gluster/community#16]
For example, searching for the setting `performance.parallel-readdir` returns nothing:

![screen shot 2017-11-08 at 1 41 49 pm](https://user-images.githubusercontent.com/862951/32529108-cace0218-c48a-11e7-9861-593a6645a2c5.jpg)

Neither does `parallel-readdir`:

![screen shot 2017-11-08 at 1 41 58 pm](https://user-images.githubusercontent.com/862951/32529107-ca972bd0-c48a-11e7-865d-6fa6bf79e9da.jpg)

Although this is a valid configuration option:

```shell
gluster volume get test_static parallel-readdir
Option                                  Value
------                                  -----
performance.parallel-readdir            true
```

---

By contrast, searching for the setting `network.ping-timeout` does return something:

![screen shot 2017-11-08 at 1 42 28 pm](https://user-images.githubusercontent.com/862951/32529106-ca5fb808-c48a-11e7-98d0-c3401a19a3da.jpg)

**Comment by nigelbabu** [comment]
Huh. That's weird. I could swear I fixed this to not use the RTD search. Assigning this to myself.
