### ISSUE TITLE
Gluster Board

### ISSUE THREAD

**Issue by joejulian** [gluster/community#18]
Determine if one is needed. 

Answer these questions first:

- [ ] What would a board be responsible for? 
- [ ] What are some examples of the duties of other boards?
- [ ] Would Red Hat support this or hinder it?

Answer these questions second:
- [ ] What should the makeup of the board be?
- [ ] How can we measure success?
- Hopefully more questions to come from the comments.

**Comment by joejulian** [comment]
### CNCF

> The CNCF Governing Board (GB) will be responsible for marketing and other business oversight and budget decisions for the CNCF. The GB does not make technical decisions for the CNCF, other than working with the TOC to set the overall scope for the CNCF.

**Comment by joejulian** [comment]
### ASF

> The Board of Directors of The Apache Software Foundation (ASF) is responsible for management and oversight of the business and affairs of the corporation in accordance with the Bylaws. This includes management of the corporate assets (funds, intellectual property, trademarks, and support equipment), appointment of a President and corporate officers managing the core operations of the ASF, and allocation of corporate resources for the benefit of Apache projects.

The corporation is Red Hat. They own the IP, trademarks, and equipment. The only funding is from Red Hat (at this time). Without incorporation, there's no chance of having other funding sources.

**Comment by amye** [comment]
Question: how long ago was the conversation about a technical oversight committee? Could we revisit this?

**Comment by joejulian** [comment]
It's been plenty long ago. I'm willing. cc @vbellur

**Comment by amye** [comment]
Want to schedule a meeting on this after the break? 
@joejulian @vbellur

**Comment by vbellur** [comment]
>  Want to schedule a meeting on this after the break?

Sounds good to me!

**Comment by joejulian** [comment]
Absolutely.

**Comment by obnoxxx** [comment]
Also questions to ask:
* Why would one want to have a board?
* Why might it be useful? (Or what might it be useful for?)

**Comment by obnoxxx** [comment]
To me, it always seems a little absurd or paradox to have such a board: In a real distributed open source project with multiple companies participating, contributors follow different agendas anyways. So unless the companies subject themselves to this board for technical directions (or whatever), the board will be powerless. If there's essentially just one company, they give the direction of the project anyways. So if the in this case, a board is intended to give the developers independence of their employer in decision making, hence freedom of development, again it will only work if the company supports this (which might be doubtful).

So I'm really not sure what the purpose or the intended meaning would be of such a board. Curious to hear/learn.
