### ISSUE TITLE
Glustered - 2018 - Bologna, IT

### ISSUE THREAD

**Issue by IvanRossi** [gluster/community#19]
BioDec will host a Gluster-community meeting in Bologna (Italy) on March 8th 2018, back-to-back with Incontro Devops Italia (http://2018.incontrodevops.it) and in the same venue as the conference.

We are aiming for a half-a-day event, ATM, but can grow in length., since we have already got a reservation for a 50-people room all-day. 

Tentative program:

- 1-2 good tech talks;
- use-case presentation from Biodec.it/Datalab.es + proposed talks;
- QA/BOF

Things to discuss:

CfP:  beginning just before Christmas?.
Ticketing: we usually use Eventbrite w. a tiny subscription fee too weed out time-waster and spammers. Number of putative attendees gets much more realistic.

**Comment by amye** [comment]
@IvanRossi, need anything else here? 
CFP, eventbrite, etc?

**Comment by IvanRossi** [comment]
On Tue, 12 Dec 2017, Amye wrote:

> 
> @IvanRossi, need anything else here?
> CFP, eventbrite, etc?

Sorting few things now on our side. getting back soon...

--
Ivan Rossi, PhD - ivan AT biodec dot com
BioDec Srl, Via Calzavecchio 20/2, 40033 Casalecchio di Reno (BO), Italy
Phone: (+39)-051-0548263 - Fax: (+39)-051-7459582 - http://www.biodec.com

Occam's Taser: The most painful explanation is usually the correct one.

**Comment by abragad** [comment]
We now have a page at http://www.incontrodevops.it/events/glustered-2018/ and the ticketing options will follow very soon. Regarding the CfP, we are keeping it simple with a mail link to info@biodec.com

Also a short blog post at http://www.incontrodevops.it/2017/12/21/glustered-2018/

Very excited to have the thing rolling!

**Comment by abragad** [comment]
Free ticket registration at https://www.eventbrite.com/e/glustered-2018-tickets-41474422113

**Comment by IvanRossi** [comment]
@amye Would you modify the page on  http://www.gluster.org/events/glustered/ to have links to the relevant pages above?
We will try to make some noise on social nets and on our (local) channels, but any help is appreciated.

**Comment by amye** [comment]
All was updated before the holiday. Anything else we need to do?

**Comment by IvanRossi** [comment]
1. help in promoting (social media) is welcome. 
2. another tech talk (Gluster/K8s/Openshift integration ) would be nice to have
3. meetup kits, I guess (see #14)

**Comment by amye** [comment]
We are live on the meetup kits, http://www.gluster.org/meetup-swag-requests/ is open.

**Comment by IvanRossi** [comment]
Program is online
http://www.incontrodevops.it/events/glustered-2018/

**Comment by amye** [comment]
Marking this as closed, will put out blog posts next week about how it went!
