### ISSUE TITLE
Gluster Summit 2017 - Prague, CZ

### ISSUE THREAD

**Issue by amye** [gluster/community#3]
Date: October 27 - 28 
[Gluster Summit](https://www.gluster.org/events/summit2017)
We're at the last tail end of this, but I want to track what goes into a Gluster Summit planning anyways.

- Venue: complete
- Schedule: this process will need a separate ticket to track, but complete. 
- Catering: review week of October 9
- Evening event: review week of October 9
- Website updated: complete 
- Emails to attendees: week of October 9, October 16 x2
-- Final email with details October 25
- Slide deadline: October 13 for rough draft, October 20th for final draft 
- Swag: ordered, included custom lanyards from CZ supplier 
- Badges: at printer's as of October 4th
- A/V filming: emails need to go out today, October 6th to find volunteers
- Registration: 56 as of October 6, ask in attendee email to confirm

**Comment by amye** [comment]
Badges picked up, as of October 16.

**Comment by amye** [comment]
Registration at 75 (minus one who emailed and said not attending.)
Swag's en route to the OSS EU venue. 

Remaining: 
Set up walkthrough on Thursday afternoon and swag drop at the same time - to schedule 
Final attendee emails.

**Comment by joejulian** [comment]
Possible survey questions:

- Was there anything you wanted to learn about that wasn't covered?
- Was there any subject that was over-covered?
- How was the talk length?
  - Too short
  - Just right
  - Too Long
- How was the BoF session lengths?
- How could BoF's be better?
- How could the Summit be better?
- Are you using your swag?
- How has this summit changed your goals or expectations?
- What is the most important thing you learned?

**Comment by amye** [comment]
Adding: 
Would you attend more regional summits instead of just one? 
Virtual summits? 

Putting together today, will send out today + again on Tuesday

**Comment by amye** [comment]
Survey is live: 
http://www.gluster.org/gluster-summit-survey-2017/

**Comment by joejulian** [comment]
Should the BoF length question have the same radio buttons as the talk length?
