### ISSUE TITLE
Location of the website content these days?

### ISSUE THREAD

**Issue by justinclift** [gluster/community#31]
Just noticed a problem with the Gluster.org website... all of the links on the Consultants page are busted/nonfunctional.

Not sure where to file the bug though.  Didn't see anything obvious on the website, so figured someone would at least see it here. :smile:

Side note - the website for Datalab (www.datalab.com) appears to be offline.  Not sure if that's a temp thing, or if their entry should be removed.

**Comment by sankarshanmukhopadhyay** [comment]
@justinclift thank you for pointing this out. I am tagging @amarts here so that we can get this fixed.

**Comment by xhernandez** [comment]
> Side note - the website for Datalab ([www.datalab.com](http://www.datalab.com)) appears to be offline. Not sure if that's a temp thing, or if their entry should be removed.

The website for Datalab is online, but the address is incorrect. It should be http://www.datalab.es. Contact email is the same but on datalab.es domain.

**Comment by amarts** [comment]
@justinclift revisited all the links, and corrected the link of datalab.es

Should be fine now. Can you reconfirm?

**Comment by justinclift** [comment]
Still needs a bit of work:

* The mailto link for datalab is busted
* Ditto, Manhattan Computer
* When clicking on any of the logos, aside from RH, it just loads the logo.  Should go to the website of the given consultant
* The BioDec and Netbulae entries should probably the first word of their entry be turned into a link added to their website, same as the other entries

**Comment by justinclift** [comment]
Just checked again.

* The mailto link for Datalab is ok now. :smile:
* **The Manhattan Computer mailto is still broken**
* Clicking on a logo now works ok
* All of the entries now have a suitable first word or similar that can be clicked on now too. :smile:

Almost fixed... :wink:

**Comment by amarts** [comment]
> The Manhattan Computer mailto is still broken

Fixed now. Thanks for being persistent.
