### ISSUE TITLE
DevConf CZ - 2018 - Brno

### ISSUE THREAD

**Issue by amye** [gluster/community#5]
Date: Jan 26-28, 2018
[DevConfCZ](https://devconf.cz/)

- Attending? 
- Speaking?

**Comment by kshlm** [comment]
I've had my presentation about Gluster-4.0 and GD2 accepted.

**Comment by mscherer** [comment]
speaking, albeit not on Gluster.

**Comment by amye** [comment]
Given the space for this event, not likely to put a table together - but Container Native Storage?

**Comment by amye** [comment]
Posting https://devconfcz2018.sched.com/event/DJVv/gluster-40-and-gd2 to social media.

**Comment by amye** [comment]
Things for next year:
Shared Storage Table 
Demos 
Further meetings?
