### ISSUE TITLE
FOSDEM 2018 - Brussels

### ISSUE THREAD

**Issue by amye** [gluster/community#6]
Date: Feb 3-4, 2018
[FOSDEM](https://fosdem.org/)

- Stand: applied for, sharing with Ceph
- DevRoom: @nixpanic with Thiago da Silva

**Comment by nixpanic** [comment]
[CfP for the Sofware Defined Storage devroom](https://lists.fosdem.org/pipermail/fosdem/2017-October/002616.html) closes 26 November.

**Comment by amye** [comment]
@amye to build out a schedule on the website for office hours and demos at the booth.

**Comment by amye** [comment]
Other things that came up in community meeting on 8-Nov: 
 - Monitor for the stand
- Ask oVirt for a shared demo office hour type thing.
- Branded polos, 6 week deadline ahead of event.

**Comment by amye** [comment]
@nixpanic, ping on the polo shirts. I've already got some in-house, but how many do we think we need?

**Comment by kshlm** [comment]
I had my submission to do a talk on Gluster-4.0 and GD2 accepted by the Storage devroom. I also saw another accepted talk on Gluster, 'Debugging A Live Gluster File System Using .meta Directory' which I guess was submitted by @rafikc30.

I'll be needing one of those shirts!

**Comment by nixpanic** [comment]
On Tue, Dec 12, 2017 at 03:39:20PM +0000, Amye wrote:
> @nixpanic, ping on the polo shirts. I've already got some in-house, but how many do we think we need? 

I suggest that the people manning the Gluster table should wear one.
Maybe the presenters of Gluster talks too? The list of Gluster
contributors currently looks like

 - Kaushal (SDS talk on Sunday)
 - Niels de Vos (SDS devroom on Sunday) - size M
 - Kaleb Keithley
 - Raghavendra Gowdappa (Performance talk on Saturday)
 - Krutika Dhananjay (Performance talk on Saturday)
 - Manisha Saini (SDS talk on Sunday)
 - Manoj Pillai (Performance talk on Saturday)
 - Rafi KC (SDS talk on Sunday)

If we could get a proposed schedule for booth attendence (min 2 persons
at all time), that would be great. As I will be busy the whole Sunday, I
would like to roam around at least a little bit on Saturday. You can
plan me in for 2x 2 hours or so.

Thanks!

**Comment by rafikc30** [comment]
I have a talk on Sunday at 12:45, apart from that I will be mostly free and happy to be in gluster booth ,
My t-shirt size is S.

**Comment by msainiRedhat** [comment]
I have a talk on 4th Feb later evening.I am available for the rest of the time on 3rd and 4th Feb.
T-shirt size -M

**Comment by amye** [comment]
On the monitor: I've not been able to get responses on this, so I'll be bringing a portable monitor to use for demos.

**Comment by amye** [comment]
Speaking of demos, @nixpanic, @kshlm, @rafikc30, @raghavendrahg, @msainiRedhat (all the people I had GitHub usernames for) - please put your demos next to your booth schedule as well.

**Comment by amye** [comment]
Things for next year: 
Sweater order 4 weeks in advance
Demos
Portable monitor
Booth Training Meeting for Gluster attendees
